### ISSUE TITLE
When retrieving models (GET) we should also get those that have a inactive signing keys

### ISSUE THREAD

**Issue by arapulido** [ubuntu-core/identity-vault#15]
When retrieving models this is the sql query:

select m.id, brand_id, name, keypair_id, revision, authority_id, key_id from model m
 inner join keypair k on k.id = m.keypair_id and k.active
 order by name

This is not ideal, as as soon as you deactivate a signing key, the models that were connected to that signing key will disappear from the UI, making it very difficult to update them (to probably select a different key).

Instead, we should show all models, and probably have a warning column (or message in the singing key column) that the key is deactivated.

**Comment by slimjim777** [comment]
#17 Shows the status of the model.

**Comment by arapulido** [comment]
Fix Comitted
