### ISSUE TITLE
README doesn't say switch to poastgres linux user

### ISSUE THREAD

**Issue by knitzsche** [ubuntu-core/identity-vault#44]
I followed the README.md and could not run createdb.go:

$ go run tools/createdb.go 
2017/01/09 12:16:11 Error accessing the database: pq: password authentication failed for user "mylinuxusername"

I don't see a place in settings.yaml to change the psql user.

I worked around it by switching to the postgres linux user, then running the various go bits:

$ su postgres
Password: 
postgres@timbre:/home/knitzsche/go/src/github.com/ubuntu-core/identity-vault$ go run tools/createdb.go 
2017/01/09 12:19:44 Database opened successfully.
2017/01/09 12:19:44 Created the 'keypair' table.
2017/01/09 12:19:44 Created the 'model' table.
2017/01/09 12:19:44 Created the 'settings' table.
2017/01/09 12:19:44 Created the 'signinglog' table.
2017/01/09 12:19:44 Created the 'nonce' table.

Perhaps the README.md should be updated with this or similar info.

**Comment by slimjim777** [comment]
You don't need to use the postgres user, you can set up any user on the database.

The datasource field accepts the normal connection string parameters for PostgreSQL:
https://godoc.org/github.com/lib/pq

**Comment by knitzsche** [comment]
got it, thx.
