### ISSUE TITLE
MySQL support?

### ISSUE THREAD

**Issue by vpetersson** [ubuntu-core/identity-vault#45]
I see that PostgreSQL is the database used in the examples. That's a great pick. I was just curious if it is a hard requirement, or if it works on MySQL too? The reason for asking is because Google Cloud does not offer PostgreSQL as a service, but they do offer MySQL.

**Comment by slimjim777** [comment]
The app uses the Go SQL library so it can handle multiple database backends. However, the code currently only includes the PostgreSQL interface and some of the SQL may be incompatible with MySQL. So the code would need some changes to also be compatible with MySQL.

**Comment by vpetersson** [comment]
In that case, no worries. We'll run it under PG. Ws just curious.

**Comment by slimjim777** [comment]
I'll close this for now, but we can review if this becomes important for more users.
